export const INDEX_TAB_DATA_BLOB = [{
    imageUrl: "ion|android-notifications",
    imageColor: "#ff3366",
    title: "通知公告",
    content: "通知消息提示",
    count: "0",
    icon:require('../img/icon/icon-TZ.png'),
  }, {
    imageUrl: "ion|ios-bookmarks",
    imageColor: "#ffcc33",
    title: "待办",
    content: "待办信息",
    count: "0",
    icon:require('../img/icon/icon-DB.png'),
  }, {
    imageUrl: "ion|android-notifications",
    imageColor: "#ff3366",
    title: "通讯录",
    content: "搜索查询通讯信息",
    count: "0",
    icon:require('../img/icon/icon-addresslist.png'),
  }, {
    imageUrl: "ion|android-notifications",
    imageColor: "#ff3366",
    title: "系统消息",
    content: "历史消息记录",
    count: "0",
    icon:require('../img/icon/icon_message.png'),
  // }, {
  //   imageUrl: "ion|android-notifications",
  //   imageColor: "#ff3366",
  //   title: "工作联系单",
  //   content: "您的工作联系单",
  //   count: "0",
  //   icon:require('../img/icon/icon-contactlist.png'),
  }];
